### ISSUE TITLE
Make dashborad workflow retestable

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/dashboard#125]
we need to configure the prow bot to respond to /restest the command on the dashboard repo.
```yaml
    triggers:
    - repos:
      - karmada-io/karmada
      - karmada-io/website
```

/assign
