### ISSUE TITLE
expose 30486 port failure when deploying karmada-dashboard 

### ISSUE THREAD

**Issue by chenyanjunyjy** [karmada-io/dashboard#14]
I'm trying to deploy karmada-dashboard on karmada host following the README.md.

- The karmada-dashboard pod is created and the status is running
- The karmada-dashboard service is created with type of NodePort

When using netstat to check port info on karmada host, port 30486 is not listening.
Is it caused by the limitation of kind? since there is no kube-proxy running?

Thanks.

**Comment by chenyanjunyjy** [comment]
![image](https://user-images.githubusercontent.com/94947046/155675745-119ee7a9-4fe5-4eb6-a0a4-775ac9b11a41.png)
![image](https://user-images.githubusercontent.com/94947046/155676001-3298dc02-3983-4e73-9ee0-7f418ecbd47d.png)

We use "local-up-karmada.sh" to start everything.

**Comment by luoMonkeyKing** [comment]
The cluster deployed through kind is running in a docker container, which does not map 30486 to the host.
You can modify the /home/karmada/artifacts/kindClusterConfig/karmada-host.yaml file to add port mappings like this:
```
kind: Cluster
apiVersion: "kind.x-k8s.io/v1alpha4"
networking:
  apiServerAddress: "{{host_ipaddress}}"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 5443
        hostPort: 5443
        protocol: TCP
        listenAddress: "{{host_ipaddress}}"
      - containerPort: 30486
        hostPort: 30486
        protocol: TCP
        listenAddress: "0.0.0.0"
```
At the same time, add the startup parameters of ip when starting local-up-karmada.sh, for example
```
local-up-karmada.sh 192.168.X.X
```
