### ISSUE TITLE
I can't login the UI, when I use token

### ISSUE THREAD

**Issue by Erick-shi** [karmada-io/dashboard#66]
my step
```yaml
[root@k8scluster-manager tmp]# cat sa.yml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: karmada-system
  name: admin-user
[root@k8scluster-manager tmp]# cat clr.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: karmada-system
[root@k8scluster-manager tmp]#
```
```bash
 kubectl apply -f sa.yml clr.yml
```
genery the token
```bash
[root@k8scluster-manager tmp]# kubectl -n karmada-system  create token admin-user
eyJhbGciOiJSUzI1NiIsImtpZCI6ImRhdGlpSDlNZ3VUS2h1ZkZhRlhrZS1YNG1FZkFscFhIc2Z3XzEtSktzcmsifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzIxOTQ1Mjc4LCJpYXQiOjE3MjE5NDE2NzgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZGQyOTQyOWItZDgzYS00ZTI1LTg3OWEtNjg5MTY0NzkxYTIyIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrYXJtYWRhLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhZG1pbi11c2VyIiwidWlkIjoiZDI3MzMxMmMtOGZiZC00ZDQyLWE4NDctMDZjOTdhZDUyNmQ2In19LCJuYmYiOjE3MjE5NDE2NzgsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprYXJtYWRhLXN5c3RlbTphZG1pbi11c2VyIn0.Fgna9cw517osq9AdIxUu3-yHZr2EIi5L6lwzHUd4nliSoRi1b7MW3NgBY8Zf5wc-GvvcnM3l-uaBYHk3RZLpMEsjKAQfPaBf8zSkXmHcoAJCOTGu-rzcUHjgfi5t4ocNLZYsOyBA19eYQxHd8U30uzofJyGlv-eZGs3Cu3WQunsCNoEX9Xnd9Pt7I1JLPNGjBPTEtqyrndZ8YkgA_LIxQApkqGjzvxGO5rZvyWmUs-9_FePkjr6EvCKs1UykRR97DBxjB87BATZGzXiWyWfMp1LZYL98FGi_2wxg07vesJjX0vDKjvp-f2NUnKYfkydXL8-7dOLTgMwB09vEwjjPXQ
```
the karmada-apiserver log
```bash
kubectl -n karmada-system logs -f karmada-apiserver-54bc5656f4-rb898
E0725 21:11:42.472629       1 authentication.go:73] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"

```
